spring.application.name=08_Employee_Management_System

# Enable H2 console
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JDBC URL for in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true


# Hibernate DDL (optional)
spring.jpa.hibernate.ddl-auto=update
